version: "3"
services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile_mlflow
    volumes:
      - ./working/mlruns:${WORKING_DIR}/mlruns
    working_dir: ${WORKING_DIR}
    depends_on:
      - jupyter
    ports:
      - "5000:5000"
    environment:
      HOME: ${WORKING_DIR}
    command: mlflow server --backend-store-uri ${WORKING_DIR}/mlruns --default-artifact-root ${WORKING_DIR}/mlruns --host 0.0.0.0 --port 5000
    restart: always